begin;
select no_plan();

insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values
 ('12000000-0000-0000-0000-000000000001','revision-admin@test.local','{}','{"username":"revision-admin","display_name":"Revision Admin"}'),
 ('12000000-0000-0000-0000-000000000002','revision-software@test.local','{}','{"username":"revision-software","display_name":"Software"}'),
 ('12000000-0000-0000-0000-000000000003','revision-rover@test.local','{}','{"username":"revision-rover","display_name":"Rover"}'),
 ('12000000-0000-0000-0000-000000000004','revision-unused@test.local','{}','{"username":"revision-unused","display_name":"Unused"}');
update public.profiles set must_change_password=false where id::text like '12000000%';
insert into public.system_roles(user_id,role) values('12000000-0000-0000-0000-000000000001','admin');
insert into public.area_memberships(user_id,area_id) select '12000000-0000-0000-0000-000000000002',id from public.areas where slug='software';
insert into public.area_memberships(user_id,area_id) select '12000000-0000-0000-0000-000000000003',id from public.areas where slug='rover';
create function pg_temp.as_user(p_tail text) returns text language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub','12000000-0000-0000-0000-'||lpad(p_tail,12,'0'),'role','authenticated')::text,true)$$;
create temp table ids(name text primary key,id uuid);
create temp table results(name text primary key,value jsonb);
grant select on ids,results to authenticated;
create function pg_temp.id(p_name text) returns uuid language sql as $$select id from ids where name=p_name$$;
select pg_temp.as_user('1');
select public.create_announcement('Comunicazione globale','Visibile solo a staff abilitato',true,'{}',now(),null,false,false);
insert into ids select 'room',id from public.rooms where name='A27';
insert into results select 'daily',public.create_daily_availabilities(pg_temp.id('room'),'2026-09-21','2026-09-25','08:30','18:00',array[1,2,3,4,5],2,'Disponibilità di lavagna');
select is((select (value->>'count')::integer from results where name='daily'),5,'daily batch creates exactly five windows');
select is((select count(*)::integer from public.room_availabilities where series_id=(select (value->>'series_id')::uuid from results where name='daily')),5,'all five rows share a series');
select ok((select bool_and(ends_at-starts_at=interval '9 hours 30 minutes') from public.room_availabilities),'no continuous 106-hour window');
select is((select count(distinct (starts_at at time zone 'Europe/Rome')::date)::integer from public.room_availabilities),5,'all dates persisted separately');
select is((select count(*)::integer from public.room_availabilities where area_note='Disponibilità di lavagna' and max_simultaneous_interviews=2),5,'notes and capacity copied to every day');
select throws_ok($$select public.create_daily_availabilities(pg_temp.id('room'),'2026-09-20','2026-09-22','08:30','18:00',array[1,2,3,4,5,6,7],2,'')$$,'23P01',null,'overlapping batch rolls back atomically');
select is((select count(*)::integer from public.room_availabilities),5,'no partial insertion on batch conflict');
select throws_ok($$select public.create_daily_availabilities(pg_temp.id('room'),'2026-09-21','2026-09-25','18:00','08:30',array[1],1,'')$$,'P0001','INVALID_DAILY_PERIOD','overnight input rejected');

insert into public.recruitment_campaigns(id,name,starts_on,ends_on,status) values('22000000-0000-0000-0000-000000000001','Functional revision','2099-01-01','2099-12-31','active');
insert into ids values('campaign','22000000-0000-0000-0000-000000000001');
select public.activate_campaign(pg_temp.id('campaign'));
insert into ids select 'software-ca',ca.id from public.campaign_areas ca join public.areas a on a.id=ca.area_id where ca.campaign_id=pg_temp.id('campaign') and a.slug='software';
insert into ids select 'rover-ca',ca.id from public.campaign_areas ca join public.areas a on a.id=ca.area_id where ca.campaign_id=pg_temp.id('campaign') and a.slug='rover';
insert into ids select 'window',public.create_room_availability(pg_temp.id('room'),'2099-09-21 08:30+02','2099-09-21 18:00+02',2,'Future test');
select pg_temp.as_user('2');
insert into ids select 'allocation',public.claim_room_allocation(pg_temp.id('window'),pg_temp.id('software-ca'),'2099-09-21 09:00+02','2099-09-21 12:00+02');
insert into ids select 'session',public.create_session_with_slots(pg_temp.id('allocation'),'Software test',20);
insert into ids select 'slot1',id from public.slots where session_id=pg_temp.id('session') order by starts_at limit 1;
insert into ids select 'slot2',id from public.slots where session_id=pg_temp.id('session') order by starts_at offset 1 limit 1;
insert into ids select 'slot3',id from public.slots where session_id=pg_temp.id('session') order by starts_at offset 2 limit 1;
insert into results select 'token',to_jsonb(public.rotate_booking_link(pg_temp.id('session')));
create function pg_temp.token() returns text language sql as $$select value#>>'{}' from results where name='token'$$;
select lives_ok($$select public.manage_session(pg_temp.id('session'),'rename','Nome modificato')$$,'session rename works');
select lives_ok($$select public.manage_slot(pg_temp.id('slot1'),'edit','2099-09-21 09:00+02','2099-09-21 09:15+02')$$,'free slot can change duration');
select throws_ok($$select public.manage_slot(pg_temp.id('slot1'),'edit','2099-09-21 08:00+02','2099-09-21 09:15+02')$$,'P0001','SLOT_OUTSIDE_ALLOCATION','out-of-allocation slot edit rejected');
select lives_ok($$select public.manage_slot(pg_temp.id('slot1'),'close')$$,'free slot can close');
select is((select status::text from public.slots where id=pg_temp.id('slot1')),'disabled','slot disabled');
select lives_ok($$select public.manage_slot(pg_temp.id('slot1'),'reopen')$$,'slot can reopen');
select pg_temp.as_user('3');
select throws_ok($$select public.manage_session(pg_temp.id('session'),'close')$$,'P0001','FORBIDDEN','other area cannot close session');
select throws_ok($$select public.manage_slot(pg_temp.id('slot1'),'close')$$,'P0001','FORBIDDEN','other area cannot edit slot');
select is(jsonb_array_length(public.list_calendar_bookings('2099-09-20','2099-09-28')),0,'other area sees no bookings');

select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),' ','Rossi','a@studenti.unipi.it')$$,'P0001','INVALID_CANDIDATE_NAME','blank first name refused in DB');
select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),'Mario',' ','a@studenti.unipi.it')$$,'P0001','INVALID_CANDIDATE_NAME','blank surname refused in DB');
select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),'Mario','Rossi',null)$$,'P0001','INVALID_STUDENT_EMAIL','null email refused');
select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),'Mario','Rossi','')$$,'P0001','INVALID_STUDENT_EMAIL','blank email refused');
select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),'Mario','Rossi','a@gmail.com')$$,'P0001','INVALID_STUDENT_EMAIL','Gmail refused');
select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),'Mario','Rossi','a@unipi.it')$$,'P0001','INVALID_STUDENT_EMAIL','non-student UniPi refused');
select throws_ok($$select public.book_public_slot(pg_temp.token(),null,'Mario','Rossi','a@studenti.unipi.it')$$,'P0001','INVALID_SLOT','missing slot refused');
insert into results select 'booking',public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),' Mario ',' Rossi ',' MARIO@STUDENTI.UNIPI.IT ');
insert into ids select 'booking',(value->>'booking_id')::uuid from results where name='booking';
insert into ids select 'delivery',(value->>'delivery_id')::uuid from results where name='booking';
select is((select email::text from public.candidates where first_name='Mario'),'mario@studenti.unipi.it','email normalized and names trimmed');
select throws_ok($$select public.book_public_slot(pg_temp.token(),pg_temp.id('slot1'),'Other','Candidate','other@studenti.unipi.it')$$,'P0001','SLOT_UNAVAILABLE','duplicate booking blocked');
select pg_temp.as_user('2');
select throws_ok($$select public.manage_slot(pg_temp.id('slot1'),'edit','2099-09-21 09:01+02','2099-09-21 09:15+02')$$,'P0001','SLOT_HAS_BOOKINGS','booked slot cannot be moved directly');
select throws_ok($$select public.manage_slot(pg_temp.id('slot1'),'delete')$$,'P0001','SLOT_HAS_BOOKINGS','booked slot cannot be deleted');
select is(jsonb_array_length(public.list_calendar_bookings('2099-09-20','2099-09-28')),1,'area calendar lists its booking');
select lives_ok($$select public.move_booking(pg_temp.id('booking'),pg_temp.id('slot2'))$$,'booking can move to free slot');
select is((select slot_id from public.bookings where id=pg_temp.id('booking')),pg_temp.id('slot2'),'booking points to new slot');
select is((select count(*)::integer from public.email_deliveries where kind='booking_changed'),1,'change notification queued');
select is((select (payload->>'starts_at')::timestamptz from public.email_deliveries where id=pg_temp.id('delivery')),'2099-09-21 09:00+02'::timestamptz,'confirmation payload remains an immutable snapshot');
select lives_ok($$select public.manage_session(pg_temp.id('session'),'close')$$,'closing session succeeds with confirmed bookings');
select is((select status::text from public.bookings where id=pg_temp.id('booking')),'confirmed','closing does not cancel bookings');
select is((select count(*)::integer from public.booking_links where session_id=pg_temp.id('session') and status='active'),0,'closing revokes links');
select is((select count(*)::integer from public.slots where session_id=pg_temp.id('session') and status='available' and id<>pg_temp.id('slot2')),0,'closing disables free slots');
select throws_ok($$select public.get_public_booking_availability(pg_temp.token())$$,'P0001','INVALID_BOOKING_LINK','closed session token invalid');
select lives_ok($$select public.manage_session(pg_temp.id('session'),'reopen')$$,'safe session reopen succeeds');
select lives_ok($$select public.cancel_booking(pg_temp.id('booking'))$$,'booking cancellation succeeds');
select is((select status::text from public.bookings where id=pg_temp.id('booking')),'cancelled','cancellation preserves booking row');
select is((select count(*)::integer from public.email_deliveries where kind='booking_cancelled'),1,'cancellation email queued');
select lives_ok($$select public.manage_slot(pg_temp.id('slot3'),'delete')$$,'never-booked slot can be deleted');
select pg_temp.as_user('3');
select throws_ok($$select public.cancel_booking(pg_temp.id('booking'))$$,'P0001','FORBIDDEN_OR_NOT_FOUND','other area cannot cancel booking');
select pg_temp.as_user('1');
select is(jsonb_array_length(public.list_calendar_bookings('2099-09-20','2099-09-28')),1,'admin calendar includes historical cancelled booking');
select is(jsonb_array_length(public.list_calendar_bookings('2099-09-20','2099-09-28',(select id from public.areas where slug='rover'))),0,'admin area filter applied');

select ok(public.claim_email_delivery(pg_temp.id('delivery')) is not null,'pending delivery claimed');
select ok(public.claim_email_delivery(pg_temp.id('delivery')) is null,'claimed delivery cannot be claimed twice');
select public.mark_email_delivery_failed(pg_temp.id('delivery'),'GMAIL_OAUTH_FAILED',1);
select is((select status::text from public.email_deliveries where id=pg_temp.id('delivery')),'failed','provider failure tracked');
select ok((select next_attempt_at between now()+interval '29 seconds' and now()+interval '31 seconds' from public.email_deliveries where id=pg_temp.id('delivery')),'first retry in thirty seconds');
select ok(public.claim_email_delivery(pg_temp.id('delivery')) is null,'backoff respected');
update public.email_deliveries set next_attempt_at=now()-interval '1 second' where id=pg_temp.id('delivery');
select ok(public.claim_email_delivery(pg_temp.id('delivery')) is not null,'due failure reclaimed');
select public.mark_email_delivery_sent(pg_temp.id('delivery'),'mock-provider-id',1);
select is((select status::text from public.email_deliveries where id=pg_temp.id('delivery')),'sending','old worker fenced out');
select public.mark_email_delivery_sent(pg_temp.id('delivery'),'mock-provider-id',2);
select ok(public.claim_email_delivery(pg_temp.id('delivery')) is null,'sent email never reclaimed');
select lives_ok($$select public.configure_email_worker('http://127.0.0.1:54321')$$,'worker configuration uses Vault');
select ok(not public.verify_email_worker_token(repeat('0',64)),'wrong worker token denied');
select is((select count(*)::integer from cron.job where jobname='colloqui-email-queue'),1,'one minutely cron job installed');
select is((select schedule from cron.job where jobname='colloqui-email-queue'),'* * * * *','worker scheduled every minute');

select throws_ok($$update public.profiles set status='disabled' where id='12000000-0000-0000-0000-000000000001'$$,'P0001','LAST_ACTIVE_ADMIN','last admin cannot be disabled');
select throws_ok($$delete from public.system_roles where user_id='12000000-0000-0000-0000-000000000001'$$,'P0001','LAST_ACTIVE_ADMIN','last admin role cannot be deleted');
select throws_ok($$select public.check_staff_deletion('12000000-0000-0000-0000-000000000001')$$,'P0001',null,'last admin cannot be deleted');
select throws_ok($$select public.check_staff_deletion('12000000-0000-0000-0000-000000000002')$$,'P0001','HAS_HISTORY','account membership/history protected');
select lives_ok($$select public.check_staff_deletion('12000000-0000-0000-0000-000000000004')$$,'unused account eligible for deletion');
select lives_ok($$select public.acquire_staff_operation('12000000-0000-0000-0000-000000000001','12000000-0000-0000-0000-000000000004')$$,'account operation lease acquired');
select throws_ok($$select public.acquire_staff_operation('12000000-0000-0000-0000-000000000001','12000000-0000-0000-0000-000000000004')$$,'P0001','ACCOUNT_BUSY','simultaneous account operation rejected');
select lives_ok($$delete from auth.users where id='12000000-0000-0000-0000-000000000004'$$,'truly unused account can be removed through Auth cascade');
select lives_ok($$select public.update_staff_profile('12000000-0000-0000-0000-000000000001','12000000-0000-0000-0000-000000000002','SoftwareRevision','Software Revision',false,(select id from public.areas where slug='software'),'disabled')$$,'admin can edit and disable an area account');
select pg_temp.as_user('2');
select ok(not private.staff_ready(),'disabled staff denied operational access');
select throws_ok($$select public.manage_session(pg_temp.id('session'),'rename','Forbidden')$$,'P0001','FORBIDDEN','disabled staff denied RPC');
select is((select count(*)::integer from public.list_announcements()),0,'disabled staff cannot read global announcements');
select pg_temp.as_user('1');
select public.update_staff_profile('12000000-0000-0000-0000-000000000001','12000000-0000-0000-0000-000000000002','SoftwareRevision','Software Revision',false,(select id from public.areas where slug='software'),'active');
update public.profiles set must_change_password=true where id='12000000-0000-0000-0000-000000000002';
select pg_temp.as_user('2');
select throws_ok($$select public.complete_password_change()$$,'P0001','PASSWORD_CHANGE_REQUIRED','password gate cannot be bypassed with RPC');
-- Synthetic hash markers are fixture data only, not usable credentials.
update auth.users set encrypted_password='fixture-changed' where id='12000000-0000-0000-0000-000000000002';
select ok(not (select must_change_password from public.profiles where id='12000000-0000-0000-0000-000000000002'),'real Auth password update clears gate');
update auth.users set encrypted_password='fixture-reset',raw_app_meta_data='{"password_reset_nonce":"new-fixture-nonce"}' where id='12000000-0000-0000-0000-000000000002';
select ok((select must_change_password from public.profiles where id='12000000-0000-0000-0000-000000000002'),'server reset nonce enforces next password change');
select pg_temp.as_user('1');
select throws_ok($$select public.manage_campaign(pg_temp.id('campaign'),'Functional revision','2099-10-01','2099-12-31','active',false)$$,'P0001','CAMPAIGN_DATES_CONFLICT','campaign dates preserve allocations');
select throws_ok($$select public.manage_campaign(pg_temp.id('campaign'),'Functional revision',null,null,'draft',true)$$,'P0001','HAS_HISTORY','used campaign cannot be deleted');
select lives_ok($$select public.manage_campaign(pg_temp.id('campaign'),'Functional revision renamed','2099-01-01','2099-12-31','archived',false)$$,'campaign archive preserves history');
select throws_ok($$select public.create_interview_session((select allocation_id from public.interview_sessions where id=pg_temp.id('session')),'Archived campaign session')$$,'P0001','SESSION_NOT_ACTIVE','cannot create a session in an archived campaign');
insert into public.recruitment_campaigns(id,name) values('22000000-0000-0000-0000-000000000002','Unused draft');
select lives_ok($$select public.manage_campaign('22000000-0000-0000-0000-000000000002','Unused draft',null,null,'draft',true)$$,'unused draft can be deleted');
insert into public.areas(id,name,slug) values('32000000-0000-0000-0000-000000000001','Unused Area','unused-revision');
select lives_ok($$select public.manage_area('32000000-0000-0000-0000-000000000001','Edited area','edited-revision',false,false)$$,'area can be edited and disabled');
select lives_ok($$select public.manage_area('32000000-0000-0000-0000-000000000001','Edited area','edited-revision',true,false)$$,'area can be reactivated');
select lives_ok($$select public.manage_area('32000000-0000-0000-0000-000000000001','Edited area','edited-revision',true,true)$$,'unused area can be deleted');
select throws_ok($$select public.manage_area((select id from public.areas where slug='software'),'Software','software',false,true)$$,'P0001','HAS_HISTORY','used area deletion blocked');
select public.manage_area((select id from public.areas where slug='software'),'Software','software',false,false);
select lives_ok($$select public.update_staff_profile('12000000-0000-0000-0000-000000000001','12000000-0000-0000-0000-000000000002','SoftwareRevision','Software Revision',false,(select id from public.areas where slug='software'),'disabled')$$,'account in inactive area can still be disabled');
select throws_ok($$select public.update_staff_profile('12000000-0000-0000-0000-000000000001','12000000-0000-0000-0000-000000000003','RoverRevision','Rover Revision',false,(select id from public.areas where slug='software'),'active')$$,'P0001','INVALID_STAFF_DATA','cannot newly assign an inactive area');
select ok(not has_function_privilege('anon','public.book_public_slot(text,uuid,text,text,text)','execute'),'anon cannot bypass Edge validation');
select ok(not has_function_privilege('authenticated','public.update_staff_profile(uuid,uuid,text,text,boolean,uuid,public.profile_status)','execute'),'staff cannot spoof actor for privileged account RPC');
select ok(not has_function_privilege('authenticated','public.verify_email_worker_token(text)','execute'),'worker token verification service-only');
select * from finish();
rollback;
